kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see loom issue #1349
org.gradle.configuration-cache=false

archives_base_name=WorldTools
maven_group=org.waste.of.time
mod_version=1.2.8

# Fabric versions: https://fabricmc.net/develop
minecraft_version=26.2
loom_version=1.17.20
fabric_loader_version=0.19.5
fabric_api_version=0.160.0+26.2
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# Dependencies
cloth_config_version=26.2.155
mod_menu_version=20.0.2
